name: carezone
description: Medicine Reminder Flutter App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  provider: ^6.0.3
  path: ^1.7.0
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  http: ^0.13.4
  firebase_storage: ^10.2.17
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^9.5.3+1
  email_auth: ^1.0.0
  firebase_core: ^1.17.1
  google_sign_in: ^5.3.3
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/carezone.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

